apiVersion: v1
kind: Pod
metadata:
  name: workman-test
spec:
  containers:
    - name: base
      image: nvcr.io/nvidia/pytorch:24.09-py3
      #image: ghcr.io/foundation-model-stack/base:pytorch-latest-nightly-20231122
      imagePullPolicy: IfNotPresent
      command:
        - sh
        - -c
        - |
          tail -f /dev/null
      resources:
        requests:
          cpu: 10
          nvidia.com/gpu: 3
          memory: 100Gi
        limits:
          cpu: 10
          nvidia.com/gpu: 6
          memory: 500Gi
      volumeMounts:
         - name: dshm
           mountPath: "/dev/shm"
         - name: data
           mountPath: /data
         - name: modelops
           mountPath: /modelops
         - name: scratch
           mountPath: /new_data
      env:
         - name: NGPU
           value: "3"
            
  imagePullSecrets:
    - name: modelops-deps-pullsecret
  schedulerName: scheduler-plugins-scheduler
  volumes:
    - name: dshm
      emptyDir:
        medium: Memory
    - name: data
      persistentVolumeClaim:
        claimName: fms-tuning-pvc
    - name: modelops
      persistentVolumeClaim:
        claimName: modelops-deps-pvc
    - name: scratch
      persistentVolumeClaim:
        claimName: llm-alignment
