---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: job-metadata-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: job-metadata-manager
  template:
    metadata:
      labels:
        app: job-metadata-manager
    spec:
      containers:
        - name: job-metadata-manager
          image: quay.io/genai-workload-manager/job_metadata_manager
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          env:
            - name: FLASK_PORT
              value: "5000"
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: fms-tuning-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: job-metadata-manager-service
spec:
  selector:
    app: job-metadata-manager
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP

---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: job-metadata-manager-route
spec:
  to:
    kind: Service
    name: job-metadata-manager-service
  port:
    targetPort: 5000
  tls:
    termination: edge
---

