apiVersion: kubeflow.org/v1
kind: PyTorchJob
metadata:
  name: sample-pytorchjob
  namespace: fms-tuning
  annotations:
    podtype: sample
    replicas: "1"
    request: "1"
    limit: "3"
spec:
  pytorchReplicaSpecs:
    Master:
      replicas: 1
      restartPolicy: OnFailure
      template:
        metadata:
          labels:
            pod-group.scheduling.sigs.k8s.io: ft-g8bc-4k-twittercomplaints-data
        spec:
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                - matchExpressions:
                  - key: nvidia.com/gpu.product
                    operator: In
                    values:
                    - NVIDIA-A100-SXM4-80GB
          containers:
          - command:
            - sh
            - -c
            - "echo \"Environment variables set by the kubeflow training operator:\"\necho
              \"Job name :\" ft-g8bc-4k-twittercomplaints-data\necho ${MASTER_ADDR}:${MASTER_PORT}\necho
              \"PYTHONUNBUFFERED:\"${PYTHONUNBUFFERED}\necho My global rank is ${RANK}
              / ${WORLD_SIZE}\necho \"Other injected environment variables:\"\necho
              \"NVME_MOUNT_PATH: \"${NVME_MOUNT_PATH}\n#\n# User commands\n#\necho
              executing: accelerate launch  --use_fsdp --fsdp_auto_wrap_policy=TRANSFORMER_BASED_WRAP
              --fsdp_forward_prefetch=false --fsdp_offload_params=false --fsdp_sharding_strategy=FULL_SHARD
              --fsdp_state_dict_type=FULL_STATE_DICT --fsdp_cpu_ram_efficient_loading=true
              --fsdp_sync_module_states=true --rdzv_backend=static --same_network
              --num_processes=1 --num_machines=${WORLD_SIZE} --mixed_precision=no
              --dynamo_backend=no --machine_rank=${RANK} --main_process_ip=${MASTER_ADDR}
              --main_process_port=${MASTER_PORT} -m tuning.sft_trainer \naccelerate
              launch  --use_fsdp --fsdp_auto_wrap_policy=TRANSFORMER_BASED_WRAP --fsdp_forward_prefetch=false
              --fsdp_offload_params=false --fsdp_sharding_strategy=FULL_SHARD --fsdp_state_dict_type=FULL_STATE_DICT
              --fsdp_cpu_ram_efficient_loading=true --fsdp_sync_module_states=true
              --rdzv_backend=static --same_network --num_processes=1 --num_machines=${WORLD_SIZE}
              --mixed_precision=no --dynamo_backend=no --machine_rank=${RANK} --main_process_ip=${MASTER_ADDR}
              --main_process_port=${MASTER_PORT} -m tuning.sft_trainer\n"
            env:
            - name: AIMSTACK_DB
              value: /aim/aim/aimrepo
            - name: SFT_TRAINER_CONFIG_JSON_ENV_VAR
              value: ewoibW9kZWxfbmFtZV9vcl9wYXRoIjogImlibS1ncmFuaXRlL2dyYW5pdGUtOGItY29kZS1iYXNlLTRrIiwKInRyYWluaW5nX2RhdGFfcGF0aCI6ICIvY29zMS9kYXRhL3R3aXR0ZXJfY29tcGxhaW50cy5qc29uIiwKIm91dHB1dF9kaXIiOiAiL2NvczEvb3V0cHV0L3NnL2ZpbmUtdHVuZWQtZ3Jhbml0ZS04Yi1jb2RlLWJhc2UtNGstbmV3MSIsIAoKInBhY2tpbmciOiBmYWxzZSwKInJlc3BvbnNlX3RlbXBsYXRlIjogIlxuIyMjIExhYmVsOiIsCiJkYXRhc2V0X3RleHRfZmllbGQiOiAib3V0cHV0IiwKCiJwZWZ0X21ldGhvZCI6ICJub25lIiwKCiJudW1fdHJhaW5fZXBvY2hzIjogMS4wLAoibWF4X3NlcV9sZW5ndGgiOiA0MDk2LAoicGVyX2RldmljZV90cmFpbl9iYXRjaF9zaXplIjogMSwKImdyYWRpZW50X2FjY3VtdWxhdGlvbl9zdGVwcyI6IDEsCgoiZXZhbHVhdGlvbl9zdHJhdGVneSI6ICJubyIsCiJzYXZlX3N0cmF0ZWd5IjogImVwb2NoIiwKImxvZ2dpbmdfc3RlcHMiOiAxLAoKImxlYXJuaW5nX3JhdGUiOiAxZS01LAoid2FybXVwX3JhdGlvIjogMC4wMywKImxyX3NjaGVkdWxlcl90eXBlIjogImNvc2luZSIsCiJ1c2VfZmxhc2hfYXR0biI6IHRydWUsCiJ0cmFja2VyIjogImFpbSIsCiJhaW1fcmVwbyI6ICIke0FJTVNUQUNLX0RCfSIsCiJleHBlcmltZW50IjogImhlbG0tY2hhcnQtdHJhaW5pbmciCn0K
            - name: PATH
              value: /home/tuning/.local/bin:/home/tuning/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
            - name: HOME
              value: /home/tuning
            - name: HF_HOME
              value: /hfcache/.cache/huggingface
            - name: GIT_SSH_COMMAND
              value: ssh -i /tmp/.ssh/keys/id_rsa -o UserKnownHostsFile=/tmp/.ssh/hosts/known_hosts
                -vv
            image: icr.io/ftplatform/sft-trainer:wca-with-aim-9028b6d71744cf964c8f6fdcdd23ca2a3afe6c7a
            imagePullPolicy: IfNotPresent
            name: pytorch
            resources:
              limits:
                cpu: 50
                memory: 500Gi
                nvidia.com/gpu: 1
              requests:
                cpu: 50
                memory: 500Gi
                nvidia.com/gpu: 1
            volumeMounts:
            - mountPath: /cos1
              name: cos1
            - mountPath: /aim
              name: aim
            - mountPath: /hfcache
              name: hfcache
            - mountPath: /tmp/.ssh/keys
              name: private-ssh-git-deploy-key
              readOnly: true
            - mountPath: /tmp/.ssh/hosts
              name: github-known-hosts
          imagePullSecrets:
          - name: modelops-deps-pullsecret
          - name: artifactory-docker-cognitiveops
          - name: all-icr-io
          volumes:
          - name: cos1
            persistentVolumeClaim:
              claimName: my-training-cos-pvc-test1
          - name: aim
            persistentVolumeClaim:
              claimName: aim-for-ai-platform-experiments-pvc
          - name: hfcache
            persistentVolumeClaim:
              claimName: fms-tuning-pvc
          - name: private-ssh-git-deploy-key
            secret:
              optional: false
              secretName: modelops-deps-cognitiveops-ssh
          - configMap:
              name: modelops-deps-github-known-hosts
            name: github-known-hosts
